#ifndef _GA_CONFIG_HPP_INCLUDED_DSFOIU498FSADKLJSDFLKJXC43IUSDFKLJHGLKJALKSJDFLSKDFJLSFKDJSDFKLJSDFJKLSKLJFSFJKLSFJKLOIWE
#define _GA_CONFIG_HPP_INCLUDED_DSFOIU498FSADKLJSDFLKJXC43IUSDFKLJHGLKJALKSJDFLSKDFJLSFKDJSDFKLJSDFJKLSKLJFSFJKLSFJKLOIWE



namespace ga
{
    
    typedef unsigned long long  integer_type;
    typedef long double         real_type;

}//namespace ga





#endif//_GA_CONFIG_HPP_INCLUDED_DSFOIU498FSADKLJSDFLKJXC43IUSDFKLJHGLKJALKSJDFLSKDFJLSFKDJSDFKLJSDFJKLSKLJFSFJKLSFJKLOIWE


